const products = [ 
    
    {
        id: 0,
        name:"corc flip-flips",
        price: 24.99,
        instock: 14,
        description:"Theses flip-flops are from real cork and they are really comfortable. This is one of our best sellers.They are made for the beach and home.Eco friendly.",
        imgSrc: "./images/1.png",
    },
    {
        id: 1,
        name:"Avocado Love",
        price: 14.99,
        instock: 6,
        description:"These flip-flops are made for children. They can be use for everywhere and the children will love them.",
        imgSrc: "./images/2.png",
    },
    {
        id: 2,
        name:"Floral Flip-Flops",
        price: 22.99,
        instock: 20,
        description:"These flip-flops are made for women. They are designed to be comfortable for women everywhere.With this simple design, these flip-flops are made to make you feel comfortable.",
        imgSrc: "./images/3.png",
    },
    {
        id: 3,
        name:"Women Flip-Flops",
        price: 14.99,
        instock: 7,
        description:"Textured thong strap.Firm, comfortable footbed with printed logo.Synthetic outsole.",
        imgSrc: "./images/4.png",
    },
    {
        id: 4,
        name:"Plain Flip Flops",
        price: 4.99,
        instock: 8,
        description:"Perfect for lazy summer days, trips to the beach, and pottering around this pair of Plain Flip Flops are available in a variety of fun and trendy colours that will look just the part on a bright summer's day.",
        imgSrc: "./images/5.png",
    },
    {
        id: 5,
        name:"Red Flip-Flops",
        price: 17.99,
        instock: 17,
        description:"Complete your Swimwear look with our gorgeous new matching Flip Flops. Featuring your favourite Pour Moi prints, you'll be the best dressed babe on the beach!",
        imgSrc: "./images/6.png",
    },
    {
        id: 6,
        name:"Tape Flip-Flops",
        price: 23.99,
        instock: 23,
        description:"Perfect for everything and everybody.A simple design but a special feeling.",
        imgSrc: "./images/7.png",
    },
    {
        id: 7,
        name:"Men Flip-Flops",
        price: 54.99,
        instock: 3,
        description:"If you're planning some outdoor summer adventures, you'll want to set out without these. ",
        imgSrc: "./images/8.png",
    },
]